Repository SOPT-all/35-COLLABORATION-ANDROID-TWOSOMEHEART, pull requests merged in 2024-11, with the labels that each got.

#2 setting/#1: 초기 세팅
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
  .gitignore
  app/.gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/androidTest/java/org/techtown/twosomeheart/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/techtown/twosomeheart/TwosomeHeartApp.kt
  app/src/main/java/org/techtown/twosomeheart/core/Route.kt
  app/src/main/java/org/techtown/twosomeheart/core/component/DummyItem.kt
  app/src/main/java/org/techtown/twosomeheart/core/extension/Modifier.kt
  app/src/main/java/org/techtown/twosomeheart/core/util/UiState.kt
  app/src/main/java/org/techtown/twosomeheart/data/ApiFactory.kt
  app/src/main/java/org/techtown/twosomeheart/data/HeaderInterceptor.kt
  app/src/main/java/org/techtown/twosomeheart/data/dto/response/BaseResponse.kt
  app/src/main/java/org/techtown/twosomeheart/data/dto/response/DummyBaseResponse.kt
  app/src/main/java/org/techtown/twosomeheart/data/dto/response/ResponseDummyDto.kt
  app/src/main/java/org/techtown/twosomeheart/data/service/TwosomeService.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/dummy/DummyRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/dummy/DummySideEffect.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/dummy/DummyState.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/dummy/DummyViewModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/dummy/component/DummyItem.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/dummy/navigation/DummyNavigation.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainActivity.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainNavigation.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainScreen.kt
  app/src/main/java/org/techtown/twosomeheart/ui/theme/Color.kt
  app/src/main/java/org/techtown/twosomeheart/ui/theme/Theme.kt
  app/src/main/java/org/techtown/twosomeheart/ui/theme/Type.kt
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/img_app_icon.png
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/org/techtown/twosomeheart/ExampleUnitTest.kt
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: 혜음 ( ˶’ᵕ’˶ ), 💻setting💻

#5 setting/#4: 디자인 시스템 컬러 세팅
  app/src/main/java/org/techtown/twosomeheart/ui/theme/Color.kt
Labels: 세호 ♪( ›◡‹ ), 💻setting💻

#6 setting/#3: 공통 drawable 업로드
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_bag_numbered.xml
  app/src/main/res/drawable/ic_checkbox_diselect.xml
  app/src/main/res/drawable/ic_home.xml
Labels: 혜음 ( ˶’ᵕ’˶ ), 💻setting💻

#8 setting/#7: 디자인 시스템 폰트 세팅
  app/src/main/java/org/techtown/twosomeheart/ui/theme/Type.kt
  app/src/main/res/font/notosanskr_black.ttf
  app/src/main/res/font/notosanskr_bold.ttf
  app/src/main/res/font/notosanskr_extrabold.ttf
  app/src/main/res/font/notosanskr_extralight.ttf
  app/src/main/res/font/notosanskr_light.ttf
  app/src/main/res/font/notosanskr_medium.ttf
  app/src/main/res/font/notosanskr_regular.ttf
  app/src/main/res/font/notosanskr_semibold.ttf
  app/src/main/res/font/notosanskr_thin.ttf
Labels: 예인 (๑′ᴗ‵๑), 💻setting💻

#10 setting/#9: TwosomeHeartTheme 정렬
  app/src/main/java/org/techtown/twosomeheart/presentation/dummy/DummyRoute.kt
  app/src/main/java/org/techtown/twosomeheart/ui/theme/Color.kt
  app/src/main/java/org/techtown/twosomeheart/ui/theme/Theme.kt
  app/src/main/java/org/techtown/twosomeheart/ui/theme/Type.kt
Labels: 혜음 ( ˶’ᵕ’˶ ), 💻setting💻

#13 feature/#12: 수량 선택 버튼 구현
  app/src/main/java/org/techtown/twosomeheart/core/component/QuantityButton.kt
  app/src/main/res/drawable/ic_modal_minus.xml
  app/src/main/res/drawable/ic_modal_plus.xml
  app/src/main/res/drawable/ic_option_more_minus_able.xml
  app/src/main/res/drawable/ic_option_more_minus_disable.xml
  app/src/main/res/drawable/ic_option_more_plus.xml
  app/src/main/res/values/strings.xml
Labels: 혜음 ( ˶’ᵕ’˶ ), 🎨ui🎨

#21 feature/#19: 검정 버튼 구현
  app/src/main/java/org/techtown/twosomeheart/core/component/BlackBottomButton.kt
Labels: 세호 ♪( ›◡‹ ), 🎨ui🎨

#28 fix/#27: line height 적용 에러 해결
  app/src/main/java/org/techtown/twosomeheart/ui/theme/Type.kt
Labels: 혜음 ( ˶’ᵕ’˶ ), 🪛fix🪛

#18 feature/#17: 메뉴 뷰 item 구현
  app/src/main/java/org/techtown/twosomeheart/core/util/PriceFormatter.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/component/MenuItem.kt
  app/src/main/res/drawable/img_menu_banana_ameicano.png
  app/src/main/res/drawable/img_menu_banana_latte.png
  app/src/main/res/drawable/img_menu_lemon_americano.png
  app/src/main/res/drawable/img_menu_ortley_coldbrew.png
  app/src/main/res/values/strings.xml
Labels: 혜음 ( ˶’ᵕ’˶ ), 🎨ui🎨

#24 feature/#23: 공통 컴포넌트 Top bar 구현
  app/src/main/java/org/techtown/twosomeheart/core/component/Topbar.kt
Labels: 혜음 ( ˶’ᵕ’˶ ), 🎉feature🎉, 🎨ui🎨

#25 feature/#20: 메뉴 뷰구현
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainNavigation.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainScreen.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/MenuRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/MenuState.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/MenuViewModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/component/CategoryIndicator.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/component/MenuIndicator.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/model/IndicatorType.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/model/MenuModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/navigation/MenuNavigation.kt
  app/src/main/res/drawable/ic_basket.xml
  app/src/main/res/drawable/ic_menu_fab_my.xml
  app/src/main/res/drawable/ic_menu_receipt.xml
  app/src/main/res/drawable/ic_menu_search.xml
  app/src/main/res/values/strings.xml
Labels: 혜음 ( ˶’ᵕ’˶ ), 🎉feature🎉, 🎨ui🎨

#29 feature#22: 상세보기 뷰 컴포넌트 구현
  app/src/main/java/org/techtown/twosomeheart/core/component/BlackBottomButton.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuCautionChip.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/SizeTabRow.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/TemperatureTabRow.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/SizeType.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/TabType.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/TemperatureType.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/component/CategoryIndicator.kt
  app/src/main/java/org/techtown/twosomeheart/ui/theme/Type.kt
Labels: 예인 (๑′ᴗ‵๑), 🎉feature🎉, 🎨ui🎨

#32 feature/#30 detail view 구현
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailState.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailViewModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuDetailAllergyText.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuDetailContent.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuDetailPriceText.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuNutritionColumn.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/SizeTabRow.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/TemperatureTabRow.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/DetailModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/navigation/DetailNavigation.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainNavigation.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainScreen.kt
  app/src/main/res/drawable/ic_detail_arrow_down.xml
  app/src/main/res/drawable/ic_detail_arrow_up.xml
  app/src/main/res/drawable/ic_dot_nutrition_warning.xml
  app/src/main/res/values/strings.xml
Labels: 예인 (๑′ᴗ‵๑), 🎉feature🎉, 🎨ui🎨

#34 feature/#31 myMenu view 구현
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainNavigation.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainScreen.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuState.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuViewModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/CustomDialog.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuBottomSheet.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/component/MyMenuItem.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/model/MyMenuModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/navigation/MyMenuNavigation.kt
  app/src/main/res/drawable/ic_checkbox_diselect.xml
  app/src/main/res/drawable/ic_modal_checkbox_diselect.xml
  app/src/main/res/drawable/ic_mymenu_checkbox_select.xml
  app/src/main/res/drawable/ic_mymenu_move.xml
  app/src/main/res/drawable/ic_mymenu_plus.xml
  app/src/main/res/drawable/img_banana_ameicano2.png
  app/src/main/res/values/strings.xml
Labels: 세호 ♪( ›◡‹ ), 🎉feature🎉, 🎨ui🎨

#39 feature/#38: 즐겨찾기 목록 조회 API 연동
  app/src/main/java/org/techtown/twosomeheart/data/dto/response/ResponseMyMenuDto.kt
  app/src/main/java/org/techtown/twosomeheart/data/service/TwosomeService.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuViewModel.kt
Labels: 세호 ♪( ›◡‹ ), 🎉feature🎉, 🙌api연동🙌

#41 feature/#26: option view 구현
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainScreen.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/option/OptionRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/option/OptionState.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/option/OptionViewModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/option/component/BottomTotalPrice.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/option/component/OptionItem.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/option/component/OptionQuantityRow.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/option/component/TwoOptionTab.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/option/model/Option.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/option/navigation/OptionNavigation.kt
  app/src/main/res/drawable/ic_option_arrow_down.xml
  app/src/main/res/drawable/ic_option_arrow_up.xml
  app/src/main/res/drawable/ic_option_reset.xml
  app/src/main/res/drawable/ic_option_x.xml
  app/src/main/res/values/strings.xml
Labels: 혜음 ( ˶’ᵕ’˶ ), 🎉feature🎉, 🎨ui🎨

#37 feature/#33 modal view 구현
  app/src/main/java/org/techtown/twosomeheart/core/component/QuantityButton.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/CoffeeBeanSelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/DetailModalBottomBar.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/DetailModalBottomButtons.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/DetailModalBottomSheet.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/PersonalCupSelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/PersonalOptionSelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/PickUpSelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/PriceQuantitySelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/SizeSelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/TemperatureSelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/CoffeeBeanType.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/PickUpType.kt
  app/src/main/res/drawable/ic_modal_arrow_right.xml
  app/src/main/res/drawable/ic_modal_bar.xml
  app/src/main/res/drawable/ic_modal_caution.xml
  app/src/main/res/drawable/ic_modal_checkbox_select.xml
  app/src/main/res/drawable/ic_modal_large_diselect.xml
  app/src/main/res/drawable/ic_modal_large_select.xml
  app/src/main/res/drawable/ic_modal_regular_diselect.xml
  app/src/main/res/drawable/ic_modal_regular_select.xml
  app/src/main/res/drawable/ic_modal_shop_able.xml
  app/src/main/res/drawable/ic_modal_shop_disable.xml
  app/src/main/res/drawable/ic_modal_star_able.xml
  app/src/main/res/drawable/ic_modal_star_disable.xml
  app/src/main/res/values/strings.xml
Labels: 예인 (๑′ᴗ‵๑), 🎉feature🎉, 🎨ui🎨

#44 feature/#42: 마이투썸 삭제 API 연동
  app/src/main/java/org/techtown/twosomeheart/data/dto/response/ResponseMyMenuDeleteDTO.kt
  app/src/main/java/org/techtown/twosomeheart/data/service/TwosomeService.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuState.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuViewModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/model/MyMenuModel.kt
  app/src/main/res/values/strings.xml
Labels: 세호 ♪( ›◡‹ ), 🎉feature🎉, 🪛fix🪛, 🙌api연동🙌

#46 feature/#45 메뉴 즐겨찾기 api 연동
  app/src/main/java/org/techtown/twosomeheart/data/HeaderInterceptor.kt
  app/src/main/java/org/techtown/twosomeheart/data/dto/request/RequestMenuLikeDto.kt
  app/src/main/java/org/techtown/twosomeheart/data/dto/response/ResponseMenuLikeDto.kt
  app/src/main/java/org/techtown/twosomeheart/data/service/TwosomeService.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailState.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailViewModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuDetailAllergyText.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/DetailModalSideEffect.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/DetailModalState.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/DetailModalBottomBar.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/DetailModalBottomButtons.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/DetailModalBottomSheet.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/PersonalCupSelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/PickUpSelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/PriceQuantitySelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/SizeSelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/TemperatureSelection.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/CoffeeBeanType.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/LikeModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/PickUpType.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/SizeType.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/model/TemperatureType.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/navigation/DetailNavigation.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainScreen.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/option/component/OptionQuantityRow.kt
  app/src/main/res/values/strings.xml
Labels: 예인 (๑′ᴗ‵๑), 🎉feature🎉, 🙌api연동🙌

#43 feature/#40: 네비게이션 통합
  app/src/main/java/org/techtown/twosomeheart/data/dto/response/ResponseMenuDetailDto.kt
  app/src/main/java/org/techtown/twosomeheart/data/service/TwosomeService.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/DetailViewModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuDetailContent.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/modal/component/DetailModalBottomSheet.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/navigation/DetailNavigation.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainNavigation.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/main/MainScreen.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/MenuRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/MenuViewModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/model/MenuModel.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/menu/navigation/MenuNavigation.kt
Labels: 혜음 ( ˶’ᵕ’˶ ), 🎉feature🎉

#50 fix/#49: Detail 컴포넌트 패딩 값 변경
  app/src/main/java/org/techtown/twosomeheart/presentation/detail/component/MenuDetailContent.kt
Labels: 혜음 ( ˶’ᵕ’˶ ), 🪛fix🪛

#54 fix/#53: My 투썸 선택 로직 수정
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuRoute.kt
  app/src/main/java/org/techtown/twosomeheart/presentation/mymenu/MyMenuViewModel.kt
Labels: 세호 ♪( ›◡‹ ), 🪛fix🪛
